apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapdeployment
  namespace: argocd
  labels:
    app: mapdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mapdeployment
  template:
    metadata:
      labels:
        app: mapdeployment
    spec:
      containers:
      - name: mapdeployment
      #toggle image between combat01 and fire01 when demonstrating to show initial and end state
        image: indhruvtyagi/demo-map:fire01
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: dockerhub-creds
---
apiVersion: v1
kind: Service
metadata:
  name: lb-mapdeployment
  namespace: argocd
spec:
  type: LoadBalancer
  selector:
    app: mapdeployment
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8000