# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: myapp
# spec:
#   selector:
#     matchLabels:
#       app: myapp
#   replicas: 2
#   template:
#     metadata:
#       labels:
#         app: myapp
#     spec:
#       containers:
#       - name: myapp
#         image: nanajanashia/argocd-app:1.2
#         ports:
#         - containerPort: 8080
# Sample CV App which runs in a browser and uses your local computer camera
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: argocd
spec:
  selector:
    matchLabels:
      app: sample-app
  replicas: 1
  template:
    metadata:
      name: sample-app
      labels:
        app: sample-app
    spec:
      containers:
      - name: nginx
        image: docker.io/alanrenouf/sampleveco:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: argocd
spec:
  type: LoadBalancer
  selector:
    app: sample-app
  ports:
    - port: 80
      nodePort: 30888