apiVersion: v1
kind: Pod
metadata:
  name: register-vks-manual
  namespace: argocd
spec:
  containers:
  - name: register
    image: bitnami/kubectl:latest   # Includes kubectl pre-installed
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 3600; done"]
    stdin: true
    tty: true
  restartPolicy: Never
