apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: vks-01
  labels:
    tkg-cluster-selector: vks-01
    argocd-managed: "true"
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.156.0/20
    services:
      cidrBlocks:
        - 10.96.0.0/12
    serviceDomain: cluster.local
  topology:
    class: tanzukubernetescluster
    version: v1.32.0---vmware.6-fips-vkr.2
    variables:
      - name: vmClass
        value: best-effort-xsmall
      - name: storageClass
        value: k8s-storage-policy
    controlPlane:
      replicas: 1
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: os-name=photon
    workers:
      machineDeployments:
        - class: node-pool
          name: tkg-cluster-nodepool-945p
          replicas: 2
          metadata:
            annotations:
              run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu
          variables:
            overrides:
              - name: volumes
                value:
                  - name: containerd
                    mountPath: /var/lib/containerd
                    storageClass: k8s-storage-policy
                    capacity: 5Gi