apiVersion: v1
kind: Service
metadata:
  name: lb-mapdeployment
  namespace: argocd
spec:
  type: LoadBalancer
  selector:
    app: mapdeployment
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8000