apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dhruvtyagi2015/Desired-State-VCF-Edge-Demo.git'
    targetRevision: main
    path: apps/vm-app
    directory:
      recurse: true
  destination:
    server: 'https://10.1.8.207:443'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true